name: "Terraform Destroy"
description: "Destroy resources created by Terraform"

on:
  workflow_dispatch:  # Esto permite ejecutarlo manualmente desde GitHub

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # si lo usas

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init
        working-directory: 18-cicd-github-actions

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: 18-cicd-github-actions
