name: "Terraform CI/CD with GitHub Actions"
description: "This workflow deploys an EC2 instance using Terraform and GitHub Actions."

on:
  push:
    branches: [master]
    paths:
      - "18-cicd-github-actions/**"
      - ".github/workflows/terraform.yml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Initialize Terraform
        run: cd 18-cicd-github-actions && terraform init

      - name: Validate Terraform configuration
        run: cd 18-cicd-github-actions && terraform validate

      - name: Plan Terraform deployment
        run: cd 18-cicd-github-actions && terraform plan

      - name: Apply Terraform deployment
        run: cd 18-cicd-github-actions && terraform apply -auto-approve # este comando aplica los cambios sin pedir confirmación

      - name: ✅ Output EC2 instance details
        run: echo "EC2 Instance deployed successfully!"